# serverless.yml (versión corregida)
service: inmobiliaria-api
app: luisitocomunica
org: luisitocomunica

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 1024
  timeout: 20

  # --- INICIO CORRECCIÓN 1: Configuración de CORS para v4 ---
  # Se mueve la configuración de CORS aquí
  httpApi:
    cors: true
  # --- FIN CORRECCIÓN 1 ---

  # --- INICIO CORRECCIÓN 2: Usar un rol de IAM existente ---
  # Se elimina la sección "iam:" y se reemplaza con "role:"
  # Pega aquí el ARN del rol que encontraste en el Paso 1
  role: arn:aws:iam::637423185634:role/LabRole
  # --- FIN CORRECCIÓN 2 ---

functions:
  getDashboardMetrics:
    handler: handler.get_dashboard_metrics
    events:
      - httpApi:
          path: /metrics
          method: get
          # La propiedad "cors: true" se elimina de aquí

# Plugin para empaquetar las dependencias de Python
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true